spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: sa
    password:

    url: jdbc:h2:mem:appdbG
    data:
      learning: git
        hello
    url: jdbc:h2:mem:appdb
data:
   learning: git

